[project]
name = "yohane"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[dependencies]
python = "~=3.12.0"
ffmpeg = ">=4.4,<7"
yt-dlp = ">=2025.2.19,<2026"

[pypi-dependencies]
yohane = { path = ".", extras = ["cli"], editable = true }
yohane-cli = { path = "yohane-cli", editable = true }
vocal-remover = { git = "https://github.com/Japan7/vocal-remover.git", branch = "6.0.0b4" }
ipykernel = ">=6.29.5, <7"
pip = ">=25.0.1,<26"
mecab-python3 = ">=1.0.10, <2"
unidic = ">=1.1.0, <2"
uroman = ">=1.3.1.1, <2"
beautifulsoup4 = ">=4.13.3, <5"
lxml = ">=5.3.1, <6"
